[package]
name = "longtime"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
chrono-tz = "0.10.3"
clap = { version = "4.5.37", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
